# Generated by Django 4.0.3 on 2022-03-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(default=' ', verbose_name=''),
            preserve_default=False,
        ),
    ]
